/**
 * Schema class for the JSON-compatible envelope produced by {@link seal}.
 *
 * @since 0.1.0
 * @category schemas
 * @module
 */
import { Schema } from "effect"
import { SealAlgorithm } from "./SealAlgorithm.js"

/**
 * Stores an algorithm discriminator and separately encoded nonce and authenticated ciphertext.
 *
 * @remarks
 * The schema validates the algorithm literal and requires string fields; it does not validate
 * base64url syntax, nonce length, ciphertext length, or authenticity. Use {@link unseal} for those
 * checks. The envelope contains no key material, and callers remain responsible for key storage.
 *
 * @since 0.1.0
 * @category schemas
 */
export class SealedEnvelope extends Schema.Class<SealedEnvelope>("SealedEnvelope")({
  /** Algorithm used by {@link unseal} for cipher dispatch. */
  algorithm: SealAlgorithm,
  /** Unpadded base64url nonce generated by the encrypt operation. */
  nonce: Schema.String,
  /** Unpadded base64url ciphertext including its appended authentication tag. */
  ciphertext: Schema.String
}) {}
