import { describe, expect, it } from "@effect/vitest"
import { Effect } from "effect"

import * as EffectSearch from "../../src/index.js"

describe("effect-search public api", () => {
  it.effect("exports primary namespaces", () =>
    Effect.sync(() => {
      expect(EffectSearch.SearchSpace).toBeDefined()
      expect(EffectSearch.Sampler).toBeDefined()
      expect(EffectSearch.Study).toBeDefined()
      expect(EffectSearch.Study.open).toBeDefined()
      expect(EffectSearch.Study.ask).toBeDefined()
      expect(EffectSearch.Study.tell).toBeDefined()
      expect(EffectSearch.Study.fail).toBeDefined()
      expect(EffectSearch.Study.cancel).toBeDefined()
      expect(EffectSearch.Study.result).toBeDefined()
      expect(EffectSearch.Study.snapshot).toBeDefined()
      expect(EffectSearch.Study.events).toBeDefined()
      expect(EffectSearch.Study.streamFromEmitter).toBeDefined()
      expect(EffectSearch.Study.StudyHandle).toBeDefined()
      expect(EffectSearch.Study.askTellProcedureCatalog).toBeDefined()
      expect(EffectSearch.Trial).toBeDefined()
      expect(EffectSearch.StudyEvent).toBeDefined()
      expect(EffectSearch.Pareto).toBeDefined()
      expect(EffectSearch.Pareto.objectiveFrontierHoldings).toBeDefined()
      expect(EffectSearch.Pareto.objectiveFrontierWeights).toBeDefined()
      expect(EffectSearch.Pareto.objectiveHoldingWeights).toBeDefined()
      expect(EffectSearch.Pareto.dominatedIndices).toBeDefined()
      expect(EffectSearch.Pareto.frontierSnapshot).toBeDefined()
      expect(EffectSearch.Pareto.maximizeDirections).toBeDefined()
      expect(EffectSearch.Pareto.computeReferencePoint).toBeDefined()
      expect(EffectSearch.Pareto.computeMultiObjectiveWeights).toBeDefined()
      expect(EffectSearch.Contracts).toBeDefined()
      expect(EffectSearch.Contracts.ArtifactEnvelopeSchema).toBeDefined()
      expect(EffectSearch.Contracts.ArtifactEnvelopeVersion).toBeDefined()
      expect(EffectSearch.Contracts.matchEnvelope).toBeDefined()
      expect(EffectSearch.Contracts.ArtifactSink).toBeDefined()
      expect(EffectSearch.Contracts.ArtifactLineage).toBeDefined()
      expect(EffectSearch.Contracts.EnvelopeContext).toBeDefined()
      expect(EffectSearch.Contracts.EnvelopeContextLive).toBeDefined()
      expect(EffectSearch.Contracts.ArtifactPayload).toBeDefined()
      expect(EffectSearch.Contracts.fileSystemSink).toBeDefined()
      expect(EffectSearch.Contracts.readEnvelopeLog).toBeDefined()
      expect(EffectSearch.Contracts.emit).toBeDefined()
      expect(EffectSearch.Contracts.isEnvelope).toBeDefined()
      expect(EffectSearch.Errors).toBeDefined()
      expect(EffectSearch.Experimental).toBeDefined()
      expect(EffectSearch.Sampler.normalizeDeterministicSeed).toBeDefined()
      expect(EffectSearch.Sampler.sampleStratifiedRoundRobin).toBeDefined()
      expect(EffectSearch.Sampler.sampleWeightedIndices).toBeDefined()
      expect(EffectSearch.Sampler.sampleWeightedPair).toBeDefined()
      expect(EffectSearch.Sampler.selectWeightedIndexWithPolicy).toBeDefined()
    }))
})
